#web:
#  build: ./nginx
#  #volumes:
#  #  - ./web/log:/var/log/nginx
#  #  - ./web/sites-enabled:/etc/nginx/sites-enabled
#  ##links:
#  ##  - redis
#  ports:
#    - "8080:80"
web1:
  build: ./web
  volumes:
    - ./web/log:/var/log/nginx
    - ./web/sites-enabled:/etc/nginx/sites-enabled
  links:
    - redis
  ports:
    - "8080:80"
    - "8088:88"
redis:
 image: redis:2.6
 ports:
   - "6379:6379"
#app:
# build: ./app
# volumes:
#   - ./app:/usr/src/app
# #links:
# #  - redis
# ports:
#   - "3000:3000"
